// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef partner_programing_h
#define partner_programing_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern Fl_Button *btn_1;
extern Fl_Button *btn_2;
extern Fl_Button *btn_3;
extern Fl_Button *btn_4;
extern Fl_Button *btn_5;
extern Fl_Button *btn_6;
extern Fl_Button *btn_7;
extern Fl_Button *btn_8;
extern Fl_Button *btn_9;
extern Fl_Button *btn_star;
extern Fl_Button *btn_pound;
extern Fl_Button *btn_0;
extern Fl_Button *btn_clear;
extern Fl_Button *btn_call;
#include <FL/Fl_Output.H>
extern Fl_Output *output_number;
Fl_Double_Window* make_phone();
#endif
