// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "partner_programing.h"

Fl_Button *btn_1=(Fl_Button *)0;

Fl_Button *btn_2=(Fl_Button *)0;

Fl_Button *btn_3=(Fl_Button *)0;

Fl_Button *btn_4=(Fl_Button *)0;

Fl_Button *btn_5=(Fl_Button *)0;

Fl_Button *btn_6=(Fl_Button *)0;

Fl_Button *btn_7=(Fl_Button *)0;

Fl_Button *btn_8=(Fl_Button *)0;

Fl_Button *btn_9=(Fl_Button *)0;

Fl_Button *btn_star=(Fl_Button *)0;

Fl_Button *btn_pound=(Fl_Button *)0;

Fl_Button *btn_0=(Fl_Button *)0;

Fl_Button *btn_clear=(Fl_Button *)0;

Fl_Button *btn_call=(Fl_Button *)0;

Fl_Output *output_number=(Fl_Output *)0;

Fl_Double_Window* make_phone() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(170, 307);
    w = o; if (w) {/* empty */}
    { btn_1 = new Fl_Button(15, 105, 40, 40, "1");
    } // Fl_Button* btn_1
    { btn_2 = new Fl_Button(65, 105, 40, 40, "2");
    } // Fl_Button* btn_2
    { btn_3 = new Fl_Button(115, 105, 40, 40, "3");
    } // Fl_Button* btn_3
    { btn_4 = new Fl_Button(15, 155, 40, 40, "4");
    } // Fl_Button* btn_4
    { btn_5 = new Fl_Button(65, 155, 40, 40, "5");
    } // Fl_Button* btn_5
    { btn_6 = new Fl_Button(115, 155, 40, 40, "6");
    } // Fl_Button* btn_6
    { btn_7 = new Fl_Button(15, 205, 40, 40, "7");
    } // Fl_Button* btn_7
    { btn_8 = new Fl_Button(65, 205, 40, 40, "8");
    } // Fl_Button* btn_8
    { btn_9 = new Fl_Button(115, 205, 40, 40, "9");
    } // Fl_Button* btn_9
    { btn_star = new Fl_Button(15, 255, 40, 40, "*");
    } // Fl_Button* btn_star
    { btn_pound = new Fl_Button(115, 255, 40, 40, "#");
    } // Fl_Button* btn_pound
    { btn_0 = new Fl_Button(65, 255, 40, 40, "0");
    } // Fl_Button* btn_0
    { btn_clear = new Fl_Button(90, 60, 65, 35, "clear");
    } // Fl_Button* btn_clear
    { btn_call = new Fl_Button(15, 60, 65, 35, "call");
    } // Fl_Button* btn_call
    { output_number = new Fl_Output(15, 15, 140, 35);
    } // Fl_Output* text
    o->end();
  } // Fl_Double_Window* o
  return w;
}

